id: "1A-23"
title: "Ouvidoria Segura — MVP"
topic: "Convivência"
ods: [4, 10, 17]
type: "web-static"
date: "2025-06-30"
leaders: ["2025001"]
team: ["2025001", "2025002", "2025003"]
repo_url: ""
demo_url: ""
tags: ["ouvidoria", "ética", "privacidade"]
